"""add_properties_to_cards

Revision ID: 16bd3be62cd9
Revises: 1bf1dff56c54
Create Date: 2026-04-20 21:03:07.155631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16bd3be62cd9'
down_revision: Union[str, Sequence[str], None] = '1bf1dff56c54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('properties', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'properties')
    # ### end Alembic commands ###
