version: '3.8'

services:
  # 🗄️ Serviço do Banco de Dados
  db:
    image: ankane/pgvector:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=rag_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # 🐍 Serviço da Aplicação (Python)
  cli:
    image: python:3.12
    command: sleep infinity # Mantém o container ativo para rodarmos comandos
    volumes:
      - ../:/app
    working_dir: /app
    environment:
      - OPENAI_API_KEY

volumes:
  db_data: # Salva os dados do banco para não perdermos ao reiniciar